### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by huoyan1231** [Garulf/window-services#12]
Please open new issue in: https://github.com/Garulf/window-services/issues/new
1. upload log file: C:\Users\huoyan1231\AppData\Roaming\FlowLauncher\Logs\1.14.0\2023-04-01.txt
2. copy below exception message

Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\huoyan1231\AppData\Local\Programs\Python\Python38\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 04/01/2023 22:04:54
Exception:
Window Services Exception: 
Websites: https://github.com/Garulf/window-services
Author: Garulf
Version: 1.1.5
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\huoyan1231\AppData\Local\FlowLauncher\app-1.14.0\Plugins\Window Services-1.1.5\run.py", line 12, in <module>
    WindowServices()
  File "C:\Users\huoyan1231\AppData\Local\FlowLauncher\app-1.14.0\Plugins\Window Services-1.1.5\lib\flox\flox.py", line 104, in __init__
    super().__init__()
  File "C:\Users\huoyan1231\AppData\Local\FlowLauncher\app-1.14.0\Plugins\Window Services-1.1.5\lib\flox\launcher.py", line 24, in __init__
    methods = inspect.getmembers(self, predicate=inspect.ismethod)
  File "C:\Users\huoyan1231\AppData\Local\Programs\Python\Python38\lib\inspect.py", line 350, in getmembers
    value = getattr(object, key)
  File "C:\Users\huoyan1231\AppData\Local\FlowLauncher\app-1.14.0\Plugins\Window Services-1.1.5\lib\flox\flox.py", line 228, in app_settings
    with open(os.path.join(self.appdata, 'Settings', 'Settings.json'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\huoyan1231\\AppData\\Local\\FlowLauncher\\app-1.14.0\\Settings\\Settings.json'

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\huoyan1231\AppData\Local\FlowLauncher\app-1.14.0\Plugins\Window Services-1.1.5\run.py", line 12, in <module>
    WindowServices()
  File "C:\Users\huoyan1231\AppData\Local\FlowLauncher\app-1.14.0\Plugins\Window Services-1.1.5\lib\flox\flox.py", line 104, in __init__
    super().__init__()
  File "C:\Users\huoyan1231\AppData\Local\FlowLauncher\app-1.14.0\Plugins\Window Services-1.1.5\lib\flox\launcher.py", line 24, in __init__
    methods = inspect.getmembers(self, predicate=inspect.ismethod)
  File "C:\Users\huoyan1231\AppData\Local\Programs\Python\Python38\lib\inspect.py", line 350, in getmembers
    value = getattr(object, key)
  File "C:\Users\huoyan1231\AppData\Local\FlowLauncher\app-1.14.0\Plugins\Window Services-1.1.5\lib\flox\flox.py", line 228, in app_settings
    with open(os.path.join(self.appdata, 'Settings', 'Settings.json'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\huoyan1231\\AppData\\Local\\FlowLauncher\\app-1.14.0\\Settings\\Settings.json'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 840
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Hello @huoyan1231 

Looks like the plugin is unable to find Flow's settings file, which should be there.
Please verify this file exists: `C:\Users\huoyan1231\AppData\Local\FlowLauncher\app-1.14.0\Settings\Settings.json`

**Comment by huoyan1231** [comment]
> Owner

i move setting file to here now its work
thanks for help
