### ISSUE TITLE
Plugin crash after run

### ISSUE THREAD

**Issue by kubalav** [Garulf/window-services#4]
Plugin crash after run. It show crash window only.

<details>
<summary>Crash log</summary>

Flow Launcher version: 1.8.3
OS Version: Microsoft Windows NT 10.0.19041.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python310\pythonw.exe
Date: 11/08/2021 19:56:44
Exception:
System.IO.InvalidDataException: Window Services|Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\AppData\Roaming\FlowLauncher\Plugins\Window Services-1.1.1\run.py", line 12, in <module>
    WindowServices()
  File "C:\Users\WDAGUtilityAccount\AppData\Roaming\FlowLauncher\Plugins\Window Services-1.1.1\lib\flox\flox.py", line 82, in __init__
    super().__init__()
  File "C:\Users\WDAGUtilityAccount\AppData\Roaming\FlowLauncher\Plugins\Window Services-1.1.1\lib\flox\launcher.py", line 28, in __init__
    results = request_method(*request_parameters)
  File "C:\Users\WDAGUtilityAccount\AppData\Roaming\FlowLauncher\Plugins\Window Services-1.1.1\lib\flox\flox.py", line 89, in _query
    self.query(query)
  File "C:\Users\WDAGUtilityAccount\AppData\Roaming\FlowLauncher\Plugins\Window Services-1.1.1\plugin\window_services.py", line 32, in query
    services = s.get_services()
  File "C:\Users\WDAGUtilityAccount\AppData\Roaming\FlowLauncher\Plugins\Window Services-1.1.1\plugin\services.py", line 37, in get_services
    services = sp.check_output("sc query type= service state= all", shell=True).decode("utf-8").split("\r\n\r\n")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 81429: invalid start byte

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 258
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 272
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 192
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass116_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 591
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 565
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

</details>

**Comment by Garulf** [comment]
I've been working on a fix for your crash. Please try and manually install: https://github.com/Garulf/window-services/releases/tag/v1.1.5

**Comment by kubalav** [comment]
It work's, but it has wrong encoding. See screen:

![obrázok_2021-11-09_115903](https://user-images.githubusercontent.com/37414585/140912173-170ca8d2-78ef-4650-b621-96307ee921be.png)

**Comment by kubalav** [comment]
> I've been working on a fix for your crash. Please try and manually install: [`v1.1.5` (release)](https://github.com/Garulf/window-services/releases/tag/v1.1.5)
> 
> EDIT: Any chance you can run `sc query type= service state= all` in cmd.exe and post the output for me to inspect?

Here you are:
[services.txt](https://github.com/Garulf/window-services/files/7504157/services.txt)

**Comment by Garulf** [comment]
Okay, after some research I think I have this working.... Please try: https://github.com/Garulf/window-services/releases/tag/v1.1.6

**Comment by kubalav** [comment]
The issue is different, but is still persist.

![obrázok_2021-11-14_093159](https://user-images.githubusercontent.com/37414585/141673711-cd4d8774-1167-4e65-ad44-f4ad51a2f483.png)

**Comment by Garulf** [comment]
Okay, I'll keep trying... thanks for trying it out.

**Comment by Garulf** [comment]
Not sure why the encoding is so mangled. It may very well be the shell messing with the encoding. 

Re-writing and pulling directly from the source (the registry) might be for the best.

**Comment by Garulf** [comment]
Still researching a proper solution to this issue. I have a few questions that may help.
* Which version of windows are you using?
* Which language is the OS using?
* What codepage comes up when you type: `chcp` into `cmd.exe`?

**Comment by kubalav** [comment]
- Windows 10 Pro 21H1 x64, Build 19043.1348
- Slovak language
- Active code page: 852

**Comment by Garulf** [comment]
Okay, after *many* attempts to get a proper solution I think I found one.

Please try this version: https://github.com/Garulf/window-services/releases/tag/v1.1.2

If you're on FLow Launcher 1.9.0 release you can type: `pm install https://github.com/Garulf/window-services/releases/download/v1.1.2/window-services.zip` to manually install this version.
